"""Added Flask Sessions

Revision ID: 0ff680a90d84
Revises: bbb0e10d26ac
Create Date: 2021-08-08 15:45:21.284128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff680a90d84'
down_revision = 'bbb0e10d26ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=32), nullable=True),
    sa.Column('event', sa.Enum('focus', 'click', 'submit'), nullable=False, validate_strings=True),
    sa.Column('page', sa.Enum('register', 'login'), nullable=False, validate_strings=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_token'], ['session.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction')
    op.drop_table('session')
    # ### end Alembic commands ###
