"""empty message

Revision ID: 8d9eb1fa7b8e
Revises: 
Create Date: 2020-09-05 16:42:06.326275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9eb1fa7b8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('icon_url', sa.String(length=2083), nullable=True),
    sa.Column('high_score', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('credential_id', sa.String(length=250), nullable=True),
    sa.Column('ukey', sa.String(length=20), nullable=True),
    sa.Column('pub_key', sa.String(length=65), nullable=True),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('rp_id', sa.String(length=253), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pub_key'),
    sa.UniqueConstraint('ukey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
