"""Addgroup id's to interactions

Revision ID: 3c887b62ac7b
Revises: 9d30be2ca45c
Create Date: 2021-08-25 17:24:22.630206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '3c887b62ac7b'
down_revision = '9d30be2ca45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction', sa.Column('group_id', sa.String(length=32), nullable=True))
    role = table('interaction', column('group_id'))       
    op.execute(role.update().values(group_id=''))
    
    with op.batch_alter_table('interaction') as batch_op: 
        batch_op.alter_column('group_id', existing_type=sa.String(length=32), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction', 'group_id')
    # ### end Alembic commands ###
