"""Compensation tracking

Revision ID: 40021fb6fbec
Revises: 34e0ffbaf051
Create Date: 2022-02-26 16:38:09.271341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40021fb6fbec'
down_revision = '34e0ffbaf051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_complete_login', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('login_bitfield', sa.Integer(), nullable=True))
        batch_op.alter_column('credential_id',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('credential_id',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.drop_column('login_bitfield')
        batch_op.drop_column('last_complete_login')

    # ### end Alembic commands ###
