"""Fixed session foreign keys

Revision ID: 5be99266385c
Revises: 40021fb6fbec
Create Date: 2022-03-10 12:05:38.865807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be99266385c'
down_revision = '40021fb6fbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.alter_column('page',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('/register', '/login', '/add-password'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.alter_column('page',
               existing_type=sa.Enum('/register', '/login', '/add-password'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
