"""Increased string sizes for MySQL

Revision ID: 6903aa47f36d
Revises: ee821a0b378e
Create Date: 2022-01-04 10:59:25.092969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6903aa47f36d'
down_revision = 'ee821a0b378e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.alter_column('session_token',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('page',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('/register', '/login'),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('ukey',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('authenticator_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('public_key',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # https://stackoverflow.com/questions/42911904/dropping-foreign-keys-in-alembic-downgrade
    try:
       op.drop_constraint('interaction_ibfk_1', 'interaction', type_='foreignkey')
    except sa.exc.OperationalError:
       pass # Don't drop it if it doesn't already exist

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('ukey',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('display_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
        batch_op.alter_column('authenticator_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('public_key',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('page',
               existing_type=sa.Enum('/register', '/login'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.alter_column('session_token',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    
    op.create_foreign_key('interaction_ibfk_1', 'interaction', 'session', ['session_token'], ['token'])

    # ### end Alembic commands ###
