"""empty message

Revision ID: bbb0e10d26ac
Revises: 8d9eb1fa7b8e
Create Date: 2020-09-06 08:59:13.508311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb0e10d26ac'
down_revision = '8d9eb1fa7b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('pub_key', new_column_name='public_key', existing_type=sa.String(length=65))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('public_key', new_column_name='pub_key', existing_type=sa.String(length=65))
    # ### end Alembic commands ###
