"""Login Attempts Table

Revision ID: d094ddec5aa9
Revises: 40021fb6fbec
Create Date: 2022-03-11 12:12:10.063642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd094ddec5aa9'
down_revision = '40021fb6fbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.alter_column('page',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('/register', '/login', '/add-password'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.alter_column('page',
               existing_type=sa.Enum('/register', '/login', '/add-password'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
