"""Added more credential metadata, removed unused fields

Revision ID: ee821a0b378e
Revises: 3c887b62ac7b
Create Date: 2021-12-31 12:34:40.212380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee821a0b378e'
down_revision = '3c887b62ac7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attestation_format', sa.Enum('packed', 'tpm', 'android-key', 'android-safetynet', 'fido-u2f', 'apple', 'none', name='attestationformat'), nullable=True))
        batch_op.add_column(sa.Column('authenticator_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('user_verified', sa.Boolean(), nullable=True))
        batch_op.drop_column('icon_url')
        batch_op.drop_column('rp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rp_id', sa.VARCHAR(length=253), nullable=True))
        batch_op.add_column(sa.Column('icon_url', sa.VARCHAR(length=2083), nullable=True))
        batch_op.drop_column('user_verified')
        batch_op.drop_column('authenticator_id')
        batch_op.drop_column('attestation_format')

    # ### end Alembic commands ###
