name: remote ssh command
on: [release]
jobs:

  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    steps:
    - name: ssh into remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RP_ID }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: |
          whoami
          ls -al