name: migrate the DB

on: workflow_dispatch

jobs:
  deploy:
    name: Connect over SSH
    runs-on: ubuntu-latest
    steps:
    - name: ssh into remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        
        # We added -T to handle the following error:
        # https://stackoverflow.com/questions/70855915/fix-panic-provided-file-is-not-a-console-from-docker-compose-in-github-action
        script: |
          cd ~/FIDO-login
          docker-compose exec -T web python setup-db.py
