# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        env:
          FLASK_SECRET_KEY: ${{secrets.FLASK_SECRET_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          RP_ID: ${{secrets.RP_ID}}
          RP_NAME: ${{secrets.RP_NAME}}
          ORIGIN: ${{secrets.ORIGIN}}
        run: |
          pytest tests/
